### ISSUE TITLE
what to do if observableId already exists in the model?

### ISSUE THREAD

**Issue by fbergmann** [PEtab-dev/PEtab#292]
There are some cases, where the id chosen for an observable shadows an id that exists in the sbml model. Examples include 

* Parmar_PCB2019
* Bachmann_MSB2011

is that on purpose? I think this could lead to confusion and wonder if we could avoid it.

**Comment by fbergmann** [comment]
as it turns out, this happens in several other models, where before there would have been a global parameter observable_XXX for a XXX in the model. the name clash is a bit of an issue, and we for now are having issues with much more models than we had in Berlin last year.

**Comment by dweindl** [comment]
The IDs have to be unique. There must not be any parameter / species / ... with the same ID as the observable. If not clear in the docs, this needs to be updated.

In the benchmark collection models it is probably due to my script updating files to the observable table format and stripping the "observable_" prefix. Did not consider that case there. To be changed.
