### ISSUE TITLE
Clarify YAML problems specification (was: YAML problems specification)

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#301]
YAML spec currently lists problems and corresponding files as array type. Bit confused about that, shouldn't only either of the two be an array? Description also seems stale:

> One or more (SBML model, measurement, condition files) tuples.

**Comment by yannikschaelte** [comment]
The inner arrays can give additional degrees of freedom. One typical application would be that one has measurement data spread over multiple files. Then, instead of merging them all, petab can do that for you. Same for observable and visualization files. For SBML and condition files however, this would appear to make not that much sense. Indeed, currently just the first array entry is taken for those two. Agreed that we need to clarify/correct that ...

The outer array translates to a petab.CompositeProblem.

**Comment by dweindl** [comment]
Yeah, what @yannikschaelte said. Some examples / test cases coming up soon. Do you have any specific application where this becomes limiting?

**Comment by FFroehlich** [comment]
No I was just confused about documentation.
