### ISSUE TITLE
Global vs local SBML parameters

### ISSUE THREAD

**Issue by leodarrigade** [PEtab-dev/PEtab#570]
**Which problem would you like to address? Please describe.**
From my experience, PETab does not support SBML local parameters (for details on local vs global parameters, see for example p.53 of SBML 2 specification [here](https://raw.githubusercontent.com/combine-org/combine-specifications/main/specifications/files/sbml.level-2.version-5.release-1.pdf)).

**Describe the solution you would like**
It would be nice if the PEtab documentation could mention that all parameters must be declared globally.

**Comment by matthiaskoenig** [comment]
Just to comment for anybody wanting to use local parameters. You can easily convert local into global parameters via the libsbml local to global converter: https://sbml.org/software/libsbml/5.18.0/docs/formatted/cpp-api/class_s_b_m_l_local_parameter_converter.html

This is a simple SBML converter you would run over the SBML model to get a new SBML model with global instead of local parameters.
